name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [ '11', '12' ]
    name: Build and test using node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
