name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [ '12', '15' ]
    name: Build and test using node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: sudo apt install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            examples/crawl-both/report
            examples/crawl-both/tests/report
